### PR TITLE
Unload Button Fix in TTS & Inference Tabs -  Match Index Fix - Restart Applio Button Added

### PR DESCRIPTION
**Pull request by rappc87**

### CODE REVIEW

**Comment by aitronssesin** [comment]
I think the restart button is unnecesary at all, also is in the incorrect tab and is not a "restart button" is more like "clear logs" but as I say is totally unnecesary

**Review by aitronssesin — CHANGES_REQUESTED** [review]
Move the restart button to another tab

**Review by aitronssesin — CHANGES_REQUESTED** [review]
Why did you changed match_index to matchindex? Please change it to the default name

**Comment by rappc87** [comment]
> I think the restart button is unnecesary at all, also is in the incorrect tab and is not a "restart button" is more like "clear logs" but as I say is totally unnecesary

Tbh its not unnecesary. An easier solution than closing and reopening the bat file when you make a setting change like language etc.

And yes you are right.  I should have used match_index instead of matchindex.

**Comment by aitronssesin** [comment]
But you used the worng tab you should created a new tab for the button and renamed something like "Clear Console or Clear Logs"

**Comment by aitronssesin** [comment]
Okay, I might have been wrong. If it's fine, just changing the tab should work. I hadn't noticed that before restarting

**Comment by rappc87** [comment]
> Okay, I might have been wrong. If it's fine, just changing the tab should work. I hadn't noticed the code after the cls.

I changed matchindexes back to match_index and now it doesn't get the pth and index files of two separate models at startup. it gets both from the same model and when the model changes, match_index works properly. also unload buttons now make index_file empty. 

I couldn't think of a better tab to add Restart Applio to.

**Comment by aitronssesin** [comment]
Create one in the settings folder and then add it to the app.py

**Comment by rappc87** [comment]
> Create one in the settings folder and then add it to the app.py

Version tab restored to Default.
A new tab has been added to app.py.
added a new file named restart.py to the setting folder for the restart tab.

**Comment by aitronssesin** [comment]
Okay perfect I will merge it and make some changes

**Pull request merged**
