### PR TITLE
Jupyter Notebook: Docker VM

### PR DESCRIPTION
**Pull request by bastianmarin**
This really doesn't need formatting.
100 batch support for graphics with large VRAM counts
RTX 4090, supports approx 70 batch in 32k audio (twitch)

### CODE REVIEW

**Comment by Anthonyxd22** [comment]
Q 
cono

**Comment by AznamirWoW** [comment]
Batch size is not about VRAM but about the size of the dataset and the training goal.

**Comment by bastianmarin** [comment]
## Description

# This Jupyter Notebook sets up the environment for running Applio, including downloading and installing Miniconda, creating a Conda environment, cloning the Applio repository, and installing necessary dependencies. It also starts Tensorboard and the Applio application.

## Motivation and Context

# This setup is required to ensure that all necessary dependencies and environments are correctly configured for running Applio. It automates the setup process, making it easier for users to get started with Applio.

## How has this been tested?

# The setup process has been tested by running the notebook cells in sequence on a compatible system. Each step includes checks to ensure successful completion, such as verifying the existence of Miniconda and the Conda environment, and confirming the installation of dependencies.

## Screenshots (if appropriate):

imagen

## Types of changes

# What types of changes does your code introduce? Put an `x` in all the boxes that apply:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

# Go over all the following points, and put an `x` in all the boxes that apply.
# If you're unsure about any of these, don't hesitate to ask. We're here to help!

- [x] My code follows the code style of this project.
- [-] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [-] I have added tests to cover my changes.
- [x] All new and existing tests passed.

**Comment by blaisewf** [comment]
README changes are not accepted. Info could be added inside the notebook/applio docs

**Pull request closed without merging**
