### PR TITLE
✔️ · Fix Typos and load startup values from json file

### PR DESCRIPTION
**Pull request by Chilluminati91**
Fixed some typos in inference.py and added a function to load default settings from a json file. Better than hardcoded values and less annoying for people who want to use their settings.

### CODE REVIEW

**Comment by blaise-tk** [comment]
In this case I think you should make a section called template configurator and there you can create different default configurations for each section (Inference, TTS, Training...) and that when you start it will load.

This section could be in settings

**Comment by Chilluminati91** [comment]
Will take a look at it, but to keep clutter to a minimum I would instead introduce a single button in the settings tab that saves all current values to the config file. That way you can set them up in their individual tabs. Not a programmer though, just trying my best with chatgpt

**Comment by blaise-tk** [comment]
maybe @aitronssesin can help you 😁

**Comment by aitronssesin** [comment]
It's a good a idea but it needs to be implemented in all the settings and that can be time consuming. I will add your fix for the typos and add you as a coauthor.

**Pull request closed without merging**
