### PR TITLE
Various fixes.

### PR DESCRIPTION
**Pull request by sonphantrung**
See the commits below for details.

(If only some folks stop using the word "bloat" when it's the complete opposite: more of like some mistakes were made when cleaning up the code.)

### CODE REVIEW

**Comment by blaise-tk** [comment]
Hi, thanks for your PR, I'll check it out now. I understand what you say and it is clear that there are many things to clean and improve, but it is a bit complicated to do everything and testing is needed!

**Comment by sonphantrung** [comment]
> Okay, some points:
> 
> * Better not to use import * and import specifically what is necessary.
> * The Unit Test will not work because the syntax is a bit different, you can check https://github.com/blaise-tk/RVC_CLI to check it.
> * Why add value="my-project"?
> 
> I'm waiting for those changes/explanations to merge your PR, again, thank you very much!

Ok, I fixed two of your points raised, and for the name, I add "my-project" as some folks (like me) would instantly open up the GUI and click Training (or editing the settings a bit), having to input the name over and over again seems weird. I don't really like "My-Voice" from EasyGUI, and "mi-test" looks weird for beginner folks, plus, training a voice model can be a "project" in which the user attempts to make a good-sounding model :).

**Comment by blaise-tk** [comment]
Perfect, thanks!

**Comment by blaise-tk** [comment]
If you want to add me to Discord to talk about development @blaise.tk

**Pull request merged**
